# Generated by Django 3.2.13 on 2022-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tags_to_tasks'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proficiencies',
            field=models.ManyToManyField(to='tasks.Tags'),
        ),
    ]
