# Generated by Django 3.2.13 on 2022-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220712_2240'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proficiencies',
            field=models.ManyToManyField(to='tasks.Tags'),
        ),
    ]
