# Generated by Django 3.2.13 on 2022-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workload',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
