# Generated by Django 3.2.13 on 2022-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220719_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
