# Generated by Django 3.2.13 on 2022-07-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220724_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='proficiencies',
        ),
    ]
