# Generated by Django 3.2.13 on 2022-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_notification_friend_request'),
        ('users', '0003_remove_user_proficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proficiencies',
            field=models.ManyToManyField(to='tasks.Tags'),
        ),
    ]
