# Generated by Django 3.2.13 on 2022-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
