# Generated by Django 3.2.13 on 2022-06-25 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True, default='', max_length=2000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S1', 'To do'), ('S2', 'In progress'), ('S3', 'Review'), ('S4', 'Complete')], default='S1', max_length=2)),
                ('priority', models.CharField(choices=[('P1', 'Lowest'), ('P2', 'Low'), ('P3', 'Medium'), ('P4', 'High'), ('P5', 'Highest')], default='P1', max_length=2)),
                ('task_list', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasklist')),
            ],
            options={
                'ordering': ['status', '-priority', django.db.models.expressions.OrderBy(django.db.models.expressions.F('deadline'), nulls_last=True)],
            },
        ),
    ]
