# Generated by Django 3.2.13 on 2022-06-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='list_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='list_group',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskgroup'),
        ),
    ]
