# Generated by Django 3.2.13 on 2022-07-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('5', 'Lowest'), ('4', 'Low'), ('3', 'Medium'), ('2', 'High'), ('1', 'Highest')], default='Lowest', max_length=8),
        ),
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
