# Generated by Django 3.2.13 on 2022-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
