# Generated by Django 3.2.13 on 2022-07-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
