# Generated by Django 3.2.13 on 2022-07-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
